server:
  port: 8080

---
spring:
  profiles: dev
  # redis配置
  redis:
      #redis数据库名称  从0到15,默认为db0
      database: 0
      host: localhost
      # 连接redis的密码,requirpass(跟redis的master和slave同步密码masterauth两回事)
      password: ptmind
      port: 6379
---
spring:
  profiles: test
  # redis配置
  redis:
      #redis数据库名称  从0到15,默认为db0
      database: 0
      host: 172.16.100.81
      # 连接redis的密码,requirpass(跟redis的master和slave同步密码masterauth两回事)
      password: ptmind
      port: 6379
